user prompt part one of challenge 2
SeR4h/andelaweek2challenges pull request #1
Opened 2019-11-23 11:18 UTC by SeR4h

@dennisja @BillKabanga please review my code

2019-11-23 17:08 UTC, dennisja requested changes

2019-11-23 17:08 UTC, dennisja commented on usersprompt.js
> +function enterYear(number) {
Thank you for your work, This works fine. Though as a suggestion we might need to cater for negative values and very hight values i.e what happens if a user gives you say `-1` or `1000`

2019-11-23 17:08 UTC, dennisja commented on usersprompt.js
> +function enterYear(number) {
Also naming things is difficult, We could have given this function a better name based on what it does e.g `logAgeGroup` since it logs out the age group of a person

2019-11-23 17:08 UTC, dennisja commented on usersprompt.js
> +          var sum = 2019 - parseInt(x);
A naming issue again why did you name this variable sum?

2019-11-23 17:08 UTC, dennisja commented on usersprompt.js
> +
Good work on this but I noticed that your code isn't properly formatted. If you are using vscode on windows, you can format your code by pressing `Alt + Shift + f`, If you are on Linux then `Ctrl + Shift + I`. If you are using another editor or IDE, you can look for how to format its code using any search engine

2019-11-24 00:19 UTC, SeR4h commented
@dennisja all have been resolved. Please check out modified usersprompt

2019-11-25 17:54 UTC, dennisja requested changes

2019-11-25 17:54 UTC, dennisja commented on usersprompt.js
> +    if (year >= 1900) {
Lets change the order of some lines like this

1. Put `logAgeGroup(age)` below `var age = 2019 - year`
2. Only call `r.close()` at the end of the function and remove it from the `else` block

2019-11-25 17:54 UTC, dennisja commented on usersprompt.js
> +        return console.log('Out of Range,please enter valid year of birth')
We don't need the return key word

2019-11-26 09:44 UTC, SeR4h commented
@dennisja Please review the corrctions

2019-11-26 10:44 UTC, dennisja approved these changes

2019-11-26 10:44 UTC, dennisja commented on usersprompt.js
> +var readline = require('readline');
Great, You can now merge this.
You'll have to make another PR to write tests for the `logAgeGroup` function

2019-11-27 11:12 UTC, merged